site_name: Tungsten Docs
site_description: "Tungsten: The Best Home for Your ML Models"
site_url: https://tungsten-ai.github.io/tungsten-docs
theme:
  name: material
  logo: images/favicon.ico
  favicon: images/favicon.ico
  palette:
    - scheme: tungsten
  icon:
    repo: fontawesome/brands/github

repo_name: tungsten-ai/tungsten
repo_url: https://github.com/tungsten-ai/tungsten-docs

extra_css:
  - stylesheets/extra.css

nav:
  - Tungsten: index.md
  - Tutorial:
      - Getting Started: tutorial/getting_started.md
      - Inputs and Outputs: tutorial/inputs_and_outputs.md
      - The Tungsten Model: tutorial/tungsten_model.md
  # - Runners: runners.md
  # - Self-hosting: self-hosting.md
  - Model Server API: model_server_api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
