site_name: Tungstenkit Docs
site_description: "Tungstenkit: ML container made simple"
site_url: https://tungsten-ai.github.io/docs
theme:
  name: material
  logo: images/favicon.ico
  favicon: images/favicon.ico
  palette:
    - scheme: tungsten
  icon:
    repo: fontawesome/brands/github

repo_name: tungsten-ai/tungstenkit
repo_url: https://github.com/tungsten-ai/tungstenkit

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/NESFeXzFuy
    - icon: fontawesome/brands/github
      link: https://github.com/tungsten-ai

extra_css:
  - css/scheme.css
  - css/termynal.css
extra_javascript:
  - js/termynal.js

nav:
  - Introduction: index.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - Basic Example: getting_started/basic_example.md
  - Building Your Model:
      - Defining: 
        - Model Definition: building_your_model/model_definition.md
        - Input and Output: building_your_model/input_and_output.md
        - GPU Models: building_your_model/gpu_models.md
        - Using Custom Base Image: building_your_model/using_custom_base_image.md
      - Containerizing: building_your_model/containerizing.md
  - Running Models:
    - Using GPUs: running_models/using_gpus.md
    - Serving REST API: running_models/serving_rest_api.md
    - Serving Web Demo: running_models/demo.md
    - Making Single Prediction: running_models/making_a_single_prediction.md
  - Pushing and Pulling Models:
    - Pushing: pushing_and_pulling_models/pushing.md
    - Pulling: pushing_and_pulling_models/pulling.md
  - CLI Reference: cli_reference.md
  - REST API Reference: rest_api_reference.md
  - Examples:
    - Image Blurring: examples/image_blurring.md
    - Image Classification: examples/image_classification.md
    - Stable Diffusion: examples/stable_diffusion.md
    

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
