site_name: Tungsten Docs
site_description: "Tungsten: The Best Home for Your ML Models"
site_url: https://tungsten-ai.github.io/docs
theme:
  name: material
  logo: images/favicon.ico
  favicon: images/favicon.ico
  palette:
    - scheme: tungsten
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

repo_name: tungsten-ai/tungsten
repo_url: https://github.com/tungsten-ai/docs

extra_css:
  - css/scheme.css
  - css/termynal.css
extra_javascript:
  - js/termynal.js

nav:
  - Overview: index.md
  - Tungsten Model:
      - Getting Started: tungsten_model/getting_started.md
      - Use GPUs: tungsten_model/use_gpus.md
      - Input/Output: tungsten_model/input_and_output.md
      - The TungstenModel Class: tungsten_model/the_tungsten_model_class.md
      # - Tungstenkit CLI: tungsten_model/tungstenkit_cli.md
      # - Advanced Containerization: tungsten_model/advanced_containerization.md
  - Tungsten Server:
      - Getting Started: tungsten_server/getting_started.md
  # - Runners: runners.md
  # - Self-hosting: self-hosting.md
  # - Model Server API: model_server_api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
