site_name: Tungsten Docs
site_description: "Tungsten: The Best Home for Your ML Models"
site_url: https://tungsten-ai.github.io/docs
theme:
  name: material
  logo: images/favicon.ico
  favicon: images/favicon.ico
  palette:
    - scheme: tungsten
  icon:
    repo: fontawesome/brands/github

repo_name: tungsten-ai/tungstenkit
repo_url: https://github.com/tungsten-ai/tungstenkit

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://tungsten-ai-community.slack.com/
    - icon: fontawesome/brands/github
      link: https://github.com/tungsten-ai

extra_css:
  - css/scheme.css
  - css/termynal.css
extra_javascript:
  - js/termynal.js

nav:
  - Overview: index.md
  - Getting Started: getting_started.md
  - Usage:
      - Use GPUs: usage/use_gpus.md
      - Input/Output: usage/input_and_output.md
      - The TungstenModel Class: usage/the_tungsten_model_class.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
